### PR TITLE
`show_batch()` for classification task

### PR DESCRIPTION
**Pull request by markus-hinsche**
In case of a classification task: 
- set `y` to None
- show as string

Here is a usage example:
```
train_loader.show_batch(image_key=stir, 
                        label_key='label',
                        image_transform=lambda x: x.squeeze().transpose(0, 1).transpose(1,2),
                        label_transform=lambda x: f'class: {int(x.numpy())}',
                       )
```

### CODE REVIEW

**Comment by markus-hinsche** [comment]
Great thanks!

**Comment by markus-hinsche** [comment]
@kbressem Any comments on this one?

**Comment by kbressem** [comment]
I am still planning to look into the BasicViewer first. Sorry. This will still take a bit of time. 

But I plan to address this together with 2D and multi sequence viewing capabilities.

**Comment by kbressem** [comment]
Have a look at #68. It's fixed now. 

Sorry that I've ignored your changes but there were some deeper errors in the viewer classes which needed to be addressed.

**Pull request closed without merging**
