### PR TITLE
Add sanity checks to dataloader

### PR DESCRIPTION
**Pull request by kbressem**
Too often, my training fails in the transformation pipeline, which is frustrating to debug because of the two following reasons: 
1. Every time the training fails, I must restart the whole process. If problems with multiple files exist, this means multiple restarts. Given the first epoch can take a while, this can take up a lot of time. 
2. Often monai prints information on transforms if they fail. However, the object's filename leading to failure is not always given. This makes debugging challenging. 

I have added a simple sanity checker to the dataloader, that can be manually called, e.g., with `trainer.data_loader.sanity_check() or trainer.evaluator.data_loader.sanity_check()`. It iterates through all images in the dataset, but instead of raising exceptions, it prints where it would fail. This way all problematic files can be identified in one run. It also provides an overview of all unique labels in the dataset. I think this is useful, as I often have label errors (or transform errors) where additional labels were accidentally introduced or removed.

### CODE REVIEW

**Comment by kbressem** [comment]
@markus-hinsche thoughts on this? Useful for you as well?

**Comment by markus-hinsche** [comment]
Interesting, this would also help me. 

Can you show a sample output?
Will the filename of the offending image show up? Will the offending transform name show up?

Could the implementation be unit tested? (Testing that this will indeed be printed/logged)

**Comment by kbressem** [comment]
The filename shows up, the name of the transform does not. I really would like it to see the name of the transform, but I don't think this is possible. Especially, as some transforms fail quietly, e.g. resampling to all black image

**Comment by kbressem** [comment]
Tests are possible. I will switch to logging module for this (planned to do so anyway). 

But I'd prefer to do this in a future PR with unit tests for the trainer.

**Comment by markus-hinsche** [comment]
LGTM otherwise

Keno ***@***.***> schrieb am Do. 3. Nov. 2022 um 05:42:

**Pull request merged**
